config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/"
                                                "home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("pascal.users.urls", namespace="users")),
    path("club-cells/", include("pascal.club_and_cell.urls", namespace="club_cells")),
    path("events/", include("pascal.event.urls", namespace="events")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

pascal/club_and_cell/urls.py
from django.urls import path

from pascal.club_and_cell.views import ClubCellView, ClubCellListView

app_name = "club_and_cell"
urlpatterns = [
    path("create/", ClubCellView.as_view(), name="create_club_cell"),
    path("all-clubs-and-cells/", ClubCellListView.as_view(), name="all_clubs_and_cells")
]

pascal/event/urls.py
from django.urls import path

from pascal.event.views import PlaceCreateView, EventCreateView, EventListView, EventDetailsCreateView

app_name = "events"
urlpatterns = [
    path("create-place/", PlaceCreateView.as_view(), name="create_place"),
    path("create-event-details/<int:pk>/", EventDetailsCreateView.as_view(), name="create_event_details"),
    path("create-event/", EventCreateView.as_view(), name="create_event"),
    path("event-list/", EventListView.as_view(), name="event_list"),
]

pascal/users/urls.py
from django.urls import path

from pascal.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    DepartmentView
)

app_name = "users"
urlpatterns = [
    path("department/", view=DepartmentView.as_view(), name="add_department"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

pascal/club_and_cell/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from pascal.users.models import User


class ClubCell(models.Model):
    CLUB_OR_CELL = (
        ("CB", "Club"),
        ("CL", "Cell")
    )

    name = models.CharField(verbose_name=_("Name"), max_length=200)
    club_or_cell = models.CharField(verbose_name=_("Club or Cell"), max_length=2, choices=CLUB_OR_CELL, default="CB")
    faculty_head = models.ForeignKey(
        verbose_name=_("Faculty Head"), to=User, on_delete=models.CASCADE, related_name="faculty_head"
    )
    members = models.ManyToManyField(verbose_name=_("Members"), to=User, related_name="members")
    created_at = models.DateTimeField(verbose_name=_("Created At"), auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name=_("Updated At"), auto_now=True)
    is_active = models.BooleanField(verbose_name=_("Is Active"), default=True)

    def __str__(self):
        return self.name

    def get_basic_info(self):
        data = {
            "name": self.name,
            "club_or_cell": dict(self.CLUB_OR_CELL).get(self.club_or_cell)
        }
        return data

    def club_or_cell_verbose(self):
        return dict(ClubCell.CLUB_OR_CELL)[self.club_or_cell]

pascal/event/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

from pascal.club_and_cell.models import ClubCell
from pascal.users.models import User


class Place(models.Model):
    name = models.CharField(verbose_name="Name", max_length=200)
    address = models.TextField(verbose_name="Address")

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(verbose_name="Name", max_length=200)
    club_cell = models.ManyToManyField(verbose_name="Clubs and Cells", to=ClubCell, related_name="clubs_cells")
    invited_faculty = models.ManyToManyField(
        verbose_name="Invited Faculties", to=User, related_name="invited_faculties"
    )
    start_at = models.DateTimeField(verbose_name="Start On")
    end_at = models.DateTimeField(verbose_name="End On")
    place = models.ForeignKey(verbose_name="Place", to=Place, on_delete=models.DO_NOTHING)
    is_organised = models.BooleanField(verbose_name="Is Organised", default=False)

    def __str__(self):
        return self.name

    def date_verbose(self):
        return dict(ClubCell.CLUB_OR_CELL)[self.club_or_cell]


class EventDetails(models.Model):
    event = models.OneToOneField(verbose_name="Event", to=Event, on_delete=models.CASCADE, related_name="event")
    summary = models.TextField(verbose_name="Summary", null=True, blank=True)
    report_file = models.CharField(verbose_name="Report File", max_length=2000, null=True, blank=True)
    images = ArrayField(verbose_name="Images", base_field=models.CharField(max_length=2000), null=True, blank=True)
    rating = models.JSONField(verbose_name="Rating", null=True, blank=True)

    def __str__(self):
        return self.event.name

pascal/club_and_cell/forms.py
from django import forms

from pascal.club_and_cell.models import ClubCell
from pascal.users.models import User


class ClubCellForm(forms.ModelForm):
    class Meta:
        model = ClubCell
        fields = ("name", "club_or_cell", "faculty_head", "members")

    def __init__(self, *args, **kwargs):
        super(ClubCellForm, self).__init__(*args, **kwargs)
        self.fields["faculty_head"] = forms.ModelChoiceField(User.objects.filter(user_choice="FH", is_active=True))
        self.fields["members"] = forms.ModelMultipleChoiceField(User.objects.filter(
            user_choice__in=["FM", "ST"], is_active=True)
        )

pascal/event/forms.py
from django import forms
from django.contrib.admin import widgets

from pascal.event.models import Event, Place, EventDetails
from pascal.users.models import User


class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = ("name", "address")


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ("name", "club_cell", "invited_faculty", "place", "start_at", "end_at")
        widgets = {
            'start_at': forms.widgets.DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_at': forms.widgets.DateTimeInput(attrs={'type': 'datetime-local'})
        }

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields["invited_faculty"] = forms.ModelMultipleChoiceField(
            User.objects.filter(user_choice__in=["FH", "FH", "OT"])
        )


class EventDetailsForm(forms.ModelForm):
    class Meta:
        model = EventDetails
        fields = ("event", "report_file", "images", "summary")
        widgets = {
            "report_file": forms.widgets.FileInput(),
        }

    def __init__(self, *args, **kwargs):
        super(EventDetailsForm, self).__init__(*args, **kwargs)
        self.fields["images"] = forms.ImageField(
            required=False,
            widget=forms.ClearableFileInput(attrs={'multiple': True})
        )

pascal/users/forms.py
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django import forms
from django.contrib.auth import forms as admin_forms, password_validation
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from pascal.users.models import Department

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(forms.ModelForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = (
            "user_choice", "username", "first_name", "last_name", "department", "email", "phone", "sem", "password",
            "confirm_password",
        )

    def __init__(self, *args, **kwargs):
        super(UserSignupForm, self).__init__(*args, **kwargs)
        self.fields["password"].widget = forms.PasswordInput()

    def clean(self):
        cleaned_data = super(UserSignupForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        try:
            password_validation.validate_password(password, self.instance)
        except forms.ValidationError as error:
            self.add_error('password', error)

        if password != confirm_password:
            self.add_error('password', "Password and Confirm password does not match")
        return cleaned_data

    def save(self, commit=True):
        user = super(UserSignupForm, self).save(commit=True)
        user.set_password(user.password)
        user.save()
        return user


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ("name",)

pascal/club_and_cell/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, ListView
from django.utils.translation import gettext_lazy as _
from pascal.club_and_cell.forms import ClubCellForm
from pascal.club_and_cell.models import ClubCell


class ClubCellListView(LoginRequiredMixin,ListView):
    model = ClubCell
    template_name = "club_and_cell/club_and_cell_list.html"
    context_object_name = "clubs_and_cells"
    queryset = ClubCell.objects.filter(is_active=True)


class ClubCellView(LoginRequiredMixin, SuccessMessageMixin,CreateView):
    model = ClubCell
    form_class = ClubCellForm
    template_name = "club_and_cell/club_and_cell_create_form.html"
    success_message = _("Club or Cell added successfully.")
    success_url = "/club-cells/all-clubs-and-cells"

pascal/event/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, ListView, UpdateView
from django.utils.translation import gettext_lazy as _

from pascal.event.forms import PlaceForm, EventForm, EventDetailsForm
from pascal.event.models import Place, Event, EventDetails


class PlaceCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Place
    form_class = PlaceForm
    template_name = "event/event_place_list.html"
    success_url = "/events/create-place"
    success_message = _("Place added successfully.")

    def get_context_data(self, **kwargs):
        response = super(PlaceCreateView, self).get_context_data(**kwargs)
        places = Place.objects.all()
        response["places"] = places
        return response


class EventListView(LoginRequiredMixin,ListView):
    model = Event
    template_name = "events/event_list.html"
    context_object_name = "events"
    queryset = Event.objects.all().order_by("id")


class EventCreateView(LoginRequiredMixin, SuccessMessageMixin,CreateView):
    model = Event
    form_class = EventForm
    template_name = "event/event_create_form.html"
    success_message = _("Event created successfully.")
    success_url = "/events/event-list"


class EventDetailsCreateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = EventDetails
    form_class = EventDetailsForm
    template_name = "event/event_details_create_form.html"
    success_message = _("Event Details added successfully.")
    success_url = "/events/event-list"

    def get(self, *args, **kwargs):
        self.model.objects.get_or_create(event_id=kwargs.get("pk"))
        response = super(EventDetailsCreateView, self).get(*args, **kwargs)
        return response

pascal/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

pascal/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView, CreateView

from pascal.users.forms import DepartmentForm
from pascal.users.models import Department

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["first_name", "last_name", "department", "sem"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class DepartmentView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Department
    form_class = DepartmentForm
    success_url = '/users/department'
    success_message = _("Department added successfully.")

    def get_context_data(self, **kwargs):
        response = super(DepartmentView, self).get_context_data(**kwargs)
        departments = Department.objects.all()
        response["departments"] = departments
        return response

pascal/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}pascal{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="This is Club and Cell Management System Project">
  <meta name="author" content="Sahil Khirsaria">

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}
  <!-- Latest compiled and minified Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css"
    integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!-- Your stuff: Third-party CSS libraries go here -->

  <!-- This file stores project-specific CSS -->
  <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}
  <!-- Le javascript
    ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
  <!-- Bootstrap JS -->
  <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"
    integrity="sha512-OvBgP9A2JBgiRad/mM36mkzXSXaJE9BEIENnVEmeZdITvwT09xnxLtT4twkCa8m/loMbPHsvPl0T8lRGVBwjlQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <!-- Your stuff: Third-party javascript libraries go here -->

  <!-- place project specific Javascript in this file -->
  <script defer src="{% static 'js/project.js' %}"></script>

  {% endblock javascript %}

</head>

<body>

  <div class="mb-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">CACMS</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'users:add_department' %}">{% translate "Departments" %}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'club_and_cell:all_clubs_and_cells' %}">{% translate "Clubs and Cells" %}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'events:create_place' %}">{% translate "Places" %}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'events:event_list' %}">{% translate "Events" %}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% translate "My Profile" %}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
            </li>
            {% else %}
            {% if ACCOUNT_ALLOW_REGISTRATION %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
            </li>
            {% endif %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

  </div>

  <div class="container">

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}

    {% block content %}
    <p>Use this document as a way to quick start any new project.</p>
    {% endblock content %}

  </div> <!-- /container -->

  {% block modal %}{% endblock modal %}

  {% block inline_javascript %}
  {% comment %}
  Script tags with only code, no src (defer by default). To run
  with a "defer" so that you run inline code:
  <script>
    window.addEventListener('DOMContentLoaded', () => {/* Run whatever you want */ });
  </script>
  {% endcomment %}
  {% endblock inline_javascript %}
</body>

</html>